name: Access Secret via OIDC

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GCP Authentication via OIDC
        env:
          PROJECT_ID: gcp-labs-yrnmzra5
          SERVICE_ACCOUNT_EMAIL: iam-lab-7-target@gcp-labs-yrnmzra5.iam.gserviceaccount.com
        run: |
          # Fetch the OIDC token from GitHub
          export OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://iam.googleapis.com" | jq -r .value)
          
          # Exchange OIDC token for GCP access token
          gcloud auth workload-identity-pools create-credentials \
            --service-account=$SERVICE_ACCOUNT_EMAIL \
            --oidc-token=$OIDC_TOKEN \
            --project=$PROJECT_ID

      - name: Access Secret
        run: |
          gcloud secrets versions access latest --secret="flag_iam_lab_7"
