name: Check GCP Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC authentication

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2.1.3'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/97750663088/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider'
          service_account: 'iam-lab-7-target@gcp-labs-yrnmzra5.iam.gserviceaccount.com'
          activate_credentials_file: true

      - id: 'access_secret'
        name: 'Access Secret'
        env:
          PROJECT_ID: gcp-labs-yrnmzra5
        run: |
          gcloud config set project $PROJECT_ID
          gcloud secrets versions access latest --secret="flag_iam_lab_7"
