name: Access Secret

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP using OIDC
        id: auth
        env:
          PROJECT_ID: gcp-labs-yrnmzra5
          PROVIDER_ID: projects/gcp-labs-yrnmzra5/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider
          SERVICE_ACCOUNT_EMAIL: iam-lab-7-target@gcp-labs-yrnmzra5.iam.gserviceaccount.com
        run: |
          gcloud auth login --brief
          gcloud iam workload-identity-pools create-credentials \
            --provider=$PROVIDER_ID \
            --service-account=$SERVICE_ACCOUNT_EMAIL \
            --project=$PROJECT_ID
      
      - name: Access Secret
        run: |
          gcloud secrets versions access latest --secret="flag_iam_lab_7"
